# Blog settings
permalink: /yazi/:title

# variables
name: Ertuğrul Seyhan
description: Kişisel ağ adresi
repository: ertseyhan/ertseyhan.github.io
google_verification: oW8Wn02yQ5olETUp4idytJrq0lCibvXnF8szGAMeCAI

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Gems
gems: ['jekyll-feed', 'jekyll-sitemap', 'jekyll-github-metadata', 'jekyll-last-modified-at']