# Blog settings
permalink: /yazi/:title

# variables
name: Ertuğrul Seyhan
description: Kişisel ağ adresi
repository: ertseyhan/ertseyhan.github.io
google_verification: oW8Wn02yQ5olETUp4idytJrq0lCibvXnF8szGAMeCAI

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: sass

# Markdown
markdown: kramdown
-kramdown:
-  input: GFM
-  hard_wrap: false
highlighter: pygments

# seo
title: Ertuğrul Seyhan
description: Kişisel ağ adresi
url: https://ertugrulseyhan.com
author: Ertuğrul Seyhan

# assets
assets:
  compress:
    css:  sass

# Gems
gems: ['jekyll-feed', 'jekyll-sitemap', 'jekyll-github-metadata', 'jekyll-seo-tag', 'jekyll-mentions', 'jekyll-assets']