# Setup
title: Ertuğrul Seyhan
description: Kişisel ağ adresi
permalink: /yazi/:title
url: https://ertugrulseyhan.com

author:
  name: Ertuğrul Seyhan
  url: https://github.com/ertseyhan
  email: contact@ertugrulseyhan.com

# Custom variables
github_ribbon: true
enable_disqus: false

# Variables
disqus_username: ertugrulseyhan
google_analytics: UA-68370004-1
google_verification: oW8Wn02yQ5olETUp4idytJrq0lCibvXnF8szGAMeCAI
blog_repository: ertseyhan/ertseyhan.github.io

# Dependencies
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: sass
  compressed: true

assets:
  compress:
    css: sass

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - LICENSE
  - README.md
  - .gitignore

gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-github-metadata