# Settings
permalink: /yazi/:title
github_ribbon: true

# Variables
name: Ertuğrul Seyhan
description: Kişisel ağ adresi
repository: ertseyhan/ertseyhan.github.io
google_verification: oW8Wn02yQ5olETUp4idytJrq0lCibvXnF8szGAMeCAI

# Sass
sass:
  style: :compressed
  sass_dir: sass

# Markdown
markdown: kramdown
-kramdown:
-  input: GFM
-  hard_wrap: false
highlighter: rouge

# Seo
title: Ertuğrul Seyhan
description: Kişisel ağ adresi
url: https://ertugrulseyhan.com
author: Ertuğrul Seyhan

# Assets
assets:
  compress:
    css:  sass

# Gems
gems: ['jekyll-feed', 'jekyll-sitemap', 'jekyll-github-metadata', 'jekyll-seo-tag', 'jekyll-mentions', 'jekyll-assets']