# Settings
github_ribbon: true
enable_disqus: false

# Variables
name: Ertuğrul Seyhan
description: Kişisel ağ adresi
permalink: /yazi/:title
repository: ertseyhan/ertseyhan.github.io
disqus_username: ertugrulseyhan
google_verification: oW8Wn02yQ5olETUp4idytJrq0lCibvXnF8szGAMeCAI

# Sass
sass:
  style: compressed
  sass_dir: sass

# Markdown
markdown: kramdown
-kramdown:
-  input: GFM
-  hard_wrap: false
highlighter: rouge

# Seo
title: Ertuğrul Seyhan
description: Kişisel ağ adresi
url: https://ertugrulseyhan.com
author: Ertuğrul Seyhan

# Exclude files from the conversion
-exclude: ["README.md", "LICENSE", "CNAME", "Gemfile", ".gitignore"]

# Assets
assets:
  compress:
    css: sass

# Gems
gems: ['jekyll-feed', 'jekyll-sitemap', 'jekyll-github-metadata', 'jekyll-seo-tag', 'jekyll-mentions', 'jekyll-assets']